"""Email functionality for sending movie scores."""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional


def create_email_content(movies_text: str) -> tuple[str, str]:
    """Create HTML and plain text email content from movies text.

    Args:
        movies_text: Formatted movie scores text

    Returns:
        Tuple of (html_content, plain_text_content)
    """
    # Get current date for subject
    date_str = datetime.now().strftime("%B %d, %Y")

    # Create HTML email
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rotten Tomatoes Opening This Week</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f9fafb;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">

    <!-- Header -->
    <div style="background: linear-gradient(135deg, #dc2626 0%, #991b1b 100%); padding: 40px 24px; text-align: center;">
      <h1 style="margin: 0; color: #ffffff; font-size: 36px; font-weight: 800; letter-spacing: -0.5px;">
        🍅 Movie Heat
      </h1>
      <p style="margin: 12px 0 0 0; color: #fecaca; font-size: 16px; font-weight: 400;">
        Rotten Tomatoes Opening This Week
      </p>
      <p style="margin: 8px 0 0 0; color: #fee2e2; font-size: 14px;">
        {date_str}
      </p>
    </div>

    <!-- Content -->
    <div style="padding: 32px 24px;">
      <pre style="font-family: 'Courier New', monospace; font-size: 14px; line-height: 1.6; color: #111827; white-space: pre-wrap; margin: 0;">{movies_text}</pre>
    </div>

    <!-- Footer -->
    <div style="background-color: #f3f4f6; padding: 24px; text-align: center; border-top: 1px solid #e5e7eb;">
      <p style="margin: 0; color: #6b7280; font-size: 13px; line-height: 1.6;">
        Generated by Movie Heat • Weekly Newsletter<br>
        <a href="https://github.com/darthrootbeer/movie-heat" style="color: #dc2626; text-decoration: none;">View on GitHub</a>
      </p>
    </div>

  </div>
</body>
</html>
    """.strip()

    # Plain text version
    plain_text = f"""🍅 Rotten Tomatoes Opening This Week
{date_str}

{movies_text}
"""

    return html_content, plain_text


def send_email(
    movies_text: str,
    recipient_email: str,
    gmail_user: Optional[str] = None,
    gmail_password: Optional[str] = None,
) -> None:
    """Send email with movie scores.

    Args:
        movies_text: Formatted movie scores text
        recipient_email: Email address to send to
        gmail_user: Gmail address (from env GMAIL_USER if not provided)
        gmail_password: Gmail app password (from env GMAIL_APP_PASSWORD if not provided)

    Raises:
        ValueError: If required credentials are missing
        Exception: If email sending fails
    """
    # Get credentials from environment or parameters
    gmail_user = gmail_user or os.getenv("GMAIL_USER")
    gmail_password = gmail_password or os.getenv("GMAIL_APP_PASSWORD")

    if not gmail_user or not gmail_password:
        raise ValueError(
            "Gmail credentials not provided. Set GMAIL_USER and GMAIL_APP_PASSWORD "
            "environment variables or pass them as parameters."
        )

    if not recipient_email:
        raise ValueError("Recipient email address not provided")

    # Create email content
    html_content, plain_text = create_email_content(movies_text)
    date_str = datetime.now().strftime("%B %d, %Y")
    subject = f"🍅 Rotten Tomatoes Opening This Week - {date_str}"

    # Create message
    msg = MIMEMultipart("alternative")
    msg["From"] = f"Movie Heat <{gmail_user}>"
    msg["To"] = recipient_email
    msg["Subject"] = subject

    # Add both plain text and HTML versions
    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    # Send email via Gmail SMTP
    try:
        print(f"Sending email to {recipient_email}...")
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(gmail_user, gmail_password)
            server.send_message(msg)
        print("Email sent successfully!")
    except Exception as e:
        print(f"Error sending email: {e}")
        raise


def should_send_email() -> bool:
    """Check if email should be sent based on schedule (Thursdays at 12 noon Eastern).

    Note: Actual scheduling is handled by GitHub Actions cron schedule.
    This function is kept for potential future use.

    Returns:
        True if it's Thursday and time is around 12 noon Eastern, False otherwise
    """
    import pytz
    from datetime import datetime

    # Get current time in Eastern timezone
    eastern = pytz.timezone("US/Eastern")
    now_eastern = datetime.now(tz=eastern)

    # Check if it's Thursday (weekday 3, where Monday is 0)
    is_thursday = now_eastern.weekday() == 3

    # Check if it's around noon (11:30 AM - 12:30 PM Eastern)
    hour = now_eastern.hour
    minute = now_eastern.minute
    is_noon_window = hour == 12 or (hour == 11 and minute >= 30) or (hour == 12 and minute <= 30)

    return is_thursday and is_noon_window

